#! /usr/bin/env python

import sys
from array import *

print "*" * 60
print "Personal Budget - Version 1.0"
print "Mark Gong-Guy"
print "*" * 60

#Global Variables

balance = raw_input("Enter current balance: ")
running = 1
ntrans = [] 


#Functions

def addTrans(name):
    ntrans.append(name)
    print "Added: ", name

def remTrans(pos):
    del ntrans[pos]
    print "Deleted Item #", pos

#Menu Item

while running == 1:
    print "Current Balance: $", balance
    
    print "*" * 60
    print "Transaction Name"
    print '\n'.join(ntrans)
    print "*" * 60


    print "Add Transaction - 1"
    print "Remove Transaction - 2"
    print "Quit - 3"
    
    entered = input("Enter Option(1-3):")

    if entered == 1:
        enteredName = raw_input("Name of transaction: ")
        addTrans(enteredName)
    
    if entered == 2:
        enteredLoc = input("What transaction number would you like to remove: ")
        remTrans(enteredLoc)

    if entered == 3:
        sys.exit()

