#!/usr/bin/env python

import sys
from array import *

print "*" * 60
print "Todo List - Version 1.0"
print "Mark Gong-Guy"
print "*" * 60

#Initalizes todo list array
todo_list = []

while 1 == 1:
    for todo in todo_list:
        print "Todo Item : ", todo
    choose = raw_input("New item(n) or quit(q):")
    if choose == "n":
        newItem = raw_input("New todo item: ")
        todo_list.append(newItem)
    if choose == "q":
        sys.exit()

