#!/usr/bin/env python

import mysql.connector

#Connects to mysql database
db = mysql.connector.connect(user='mark', password='Mag15641994', host='localhost', database='python')

print "Database Connected"

cursor = db.cursor()

todo_name = raw_input("Enter a todo list item:")
todo_date = raw_input("Enter a todo list due date:")

cursor.execute('''INSERT into todo (todo_name, todo_date)values (%s,
        %s)''',(todo_name, todo_date))

db.commit()

#Disconnects from mysql db
db.close()
